name: Trigger Downstream Repos

# This workflow triggers dungeonchurch/homebrew when JSON files change.
# It handles two scenarios:
# 1. Manual JSON edits: triggered via push event
# 2. Automated URL updates: triggered via workflow_dispatch (since those commits use [skip ci])

on:
  # Triggered by update-asset-urls after [skip ci] commit
  workflow_dispatch:

  # Triggered by manual JSON edits (not [skip ci] commits)
  push:
    paths:
      - '*.json'
    branches:
      - main

jobs:
  trigger-homebrew:
    name: Trigger dungeonchurch/homebrew
    runs-on: docker
    container:
      image: node:20-bookworm
    steps:
      - name: Trigger downstream workflow
        uses: https://git.michaelsasser.org/actions/workflow-dispatch@main
        with:
          repository: dungeonchurch/homebrew
          workflowname: sync-upstream.yml
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
