name: Trigger Downstream Repos

# This workflow triggers dungeonchurch/homebrew when JSON files change.
# Triggered by:
# 1. validate.yml after successful validation on push to main
# 2. update-asset-urls.yaml after URL replacement (which uses [skip ci])
# 3. Manual dispatch for testing

on:
  workflow_dispatch:

jobs:
  trigger-homebrew:
    name: Trigger dungeonchurch/homebrew
    runs-on: docker
    container:
      image: node:20-bookworm
    steps:
      - name: Trigger downstream workflow
        uses: https://git.michaelsasser.org/actions/workflow-dispatch@main
        with:
          repository: dungeonchurch/homebrew
          workflowname: sync-upstream.yml
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
