name: Validate 5eTools Homebrew JSON

on:
  push:
    paths:
      - 'Dungeon Church*.json'
  pull_request:
    paths:
      - 'Dungeon Church*.json'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  validate-json:
    name: Validate JSON against 5etools schema
    runs-on: docker
    container:
      image: node:18-alpine

    steps:
    - name: Install dependencies
      run: apk add --no-cache git curl

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          /*
          !static
        sparse-checkout-cone-mode: false

    - name: Validate JSON files
      run: |
        npm install --no-save 5etools-utils

        HAS_ERRORS=0
        for file in "Dungeon Church"*.json; do
          echo "Validating \"$file\"..."
          if ! npx test-json-brew "$file"; then
            HAS_ERRORS=1
          fi
        done

        if [ "$HAS_ERRORS" -eq 1 ]; then
          echo "::error::JSON validation failed!"
          exit 1
        fi

        echo "All JSON files validated successfully!"

    - name: Trigger downstream update
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: https://git.michaelsasser.org/actions/workflow-dispatch@main
      with:
        workflowname: update-downstream.yaml
        token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}

