name: Sync Static Assets to OCI Object Storage

# This workflow syncs the contents of the 'static' folder to an OCI Object Storage bucket
# whenever changes are made to files in the static folder or when manually triggered.
#
# REQUIRED GITHUB SECRETS:
# - OCI_CLI_USER: OCID of the user (found in OCI Console > Profile > User Settings)
# - OCI_CLI_TENANCY: OCID of the tenancy (found in OCI Console > Administration > Tenancy Details)
# - OCI_CLI_FINGERPRINT: Fingerprint of the API key (generated when creating API key)
# - OCI_CLI_KEY_CONTENT: Private key content (the private key file content, including BEGIN/END lines)
# - OCI_CLI_REGION: OCI region (e.g., us-ashburn-1)
#
# To configure these secrets:
# 1. Go to your repository on GitHub
# 2. Navigate to Settings > Secrets and variables > Actions
# 3. Click "New repository secret" and add each of the required secrets
#
# For more information on obtaining these values, see:
# https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm
#
# MANUAL TRIGGER INSTRUCTIONS:
# To manually trigger this workflow:
# 1. Go to the Actions tab in your repository
# 2. Select "Sync Static Assets to OCI Object Storage" from the workflows list
# 3. Click "Run workflow" and then "Run workflow" again to confirm

on:
  # Trigger on changes to files in the static folder
  push:
    branches:
      - main
    paths:
      - 'static/**'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-assets:
    name: Sync static assets to OCI bucket
    # Only run on main branch to avoid unintended syncs from feature branches
    #if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    
    steps:
      # Run for each filetype so we can set the content-type appropriately, then run again to delete
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Sync JPG files
        uses: oracle-actions/run-oci-cli-command@v1.1
        with:
          command: os object sync -bn dungeonchurch-content --src-dir static --prefix 5e/ --include "*.jpg" --content-type image/jpeg

      - name: Sync PNG files
        uses: oracle-actions/run-oci-cli-command@v1.1
        with:
          command: os object sync -bn dungeonchurch-content --src-dir static --prefix 5e/ --include "*.png" --content-type image/png

      - name: Sync MP3 files
        uses: oracle-actions/run-oci-cli-command@v1.1
        with:
          command: os object sync -bn dungeonchurch-content --src-dir static --prefix 5e/ --include "*.mp3" --content-type audio/mpeg

      - name: Sync MP4 files
        uses: oracle-actions/run-oci-cli-command@v1.1
        with:
          command: os object sync -bn dungeonchurch-content --src-dir static --prefix 5e/ --include "*.mp4" --content-type video/mp4

      - name: Delete removed files
        uses: oracle-actions/run-oci-cli-command@v1.1
        with:
          command: os object sync -bn dungeonchurch-content --src-dir static --prefix 5e/ --delete